name: release

on:
  push:
    tags:
      - v*

jobs:

  github_build:
    name: GitHub Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Install clippy
        run: rustup component add clippy
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint (all features)
        run: cargo clippy --all-targets --all-features -- -D clippy::all
      - name: Lint (no_std)
        run: cargo clippy --all-targets --no-default-features --features alloc -- -D
          clippy::all
      - name: Lint (no_alloc)
        run: cargo clippy --all-targets --no-default-features -- -D clippy::all
      - name: Test (default)
        run: cargo test --verbose
      - name: Test (no_std)
        run: cargo test --no-default-features --features alloc --verbose
      - name: Test (no_alloc)
        run: cargo test --no-default-features --verbose

  # Publish to Crates.io
  cargo_publish:
    name: Publish Cargo Package
    needs: github_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
